### ISSUE TITLE
 非常需要，请问怎么安装？

### ISSUE THREAD

**Issue by geekbb** [anc95/writely#1]
如题

**Comment by anc95** [comment]
谢谢关注
现在只能 clone 源码，然后安装为 Chrome 扩展
不着急的话，我明天会出一个 Zip 包

**Comment by geekbb** [comment]
> 

谢谢！座等！

**Comment by IlluminateDarkheat** [comment]
> 谢谢关注 现在只能 clone 源码，然后安装为 Chrome 扩展 不着急的话，我明天会出一个 Zip 包

希望可以在Zip包所在目录也放一个解压后的文件夹，这样git pull下来后直接加载到chrome，方便后续更新

**Comment by qlaall** [comment]
能直接打包放在release吗

**Comment by neobud** [comment]
您好，下载这个zip文件在Chrome 安装报错呢

<img width="514" alt="截屏2023-03-09 下午1 47 52" src="https://user-images.githubusercontent.com/2698184/223931861-ad5462be-eb9c-4c24-b29c-1cbde2f46a3a.png">

**Comment by anc95** [comment]
@neobud 刚发布的有问题，我正在 build 马上好

**Comment by anc95** [comment]
https://github.com/anc95/writely/releases/tag/v0.0.1

已发布

**Comment by alanjustalan** [comment]
这周能上架chrome和edge插件商店吗？

**Comment by anc95** [comment]
@devyujie 好的
@alanjustalan 我还没申请，这个得看审核，尽快搞下

**Comment by alanjustalan** [comment]
笑哭

**Comment by geekbb** [comment]
> <img alt="image" width="1435" src="https://user-images.githubusercontent.com/13167934/224019316-fa55fd90-c2c7-4165-a398-bd9b7b248166.png">
> 
> 已申请，还花了 5 刀 😭

大爱！！！！！

**Comment by aceOrange** [comment]
这个是支持全网吗，还是只有飞书和知乎呢？在gmail里面怎样打开popup呀

**Comment by anc95** [comment]
@aceOrange 全网都支持

https://user-images.githubusercontent.com/13167934/224238265-69d19f7e-266a-48da-96e1-9554dee3ace3.mov


gmail 我录制了下，你看看

**Comment by aceOrange** [comment]
感谢！我工作电脑上面的gmail还是看不到popup，我感觉应该是工作电脑的原因。我在自己私人电脑上也能看到了

**Comment by Ruibin-Liu** [comment]
不支持Github issue

**Comment by anc95** [comment]
@Ruibin-Liu 我这里的也可以的
<img width="924" alt="image" src="https://user-images.githubusercontent.com/13167934/224447869-19479bc3-a6d0-4281-bfe6-b47c567f65a5.png">

我本地确实比较难复现，不过你可以试试
1. 下载最新版看一下有没有问题
2. 有可能是和其他插件冲突被遮盖
3. 看一下浏览器控制台有没有相关报错可以提供给我的

**Comment by aceOrange** [comment]
这个popup是怎么trigger的呢，是选中文字，然后就会出现一个w的图标，然后鼠标左键单击出现下拉菜单吗？可不可以把popup这个做的更explicit一点呢？比如用一组快捷键来trigger，或者是像用Google translate那样，在鼠标右键的菜单里面加一项，然后用鼠标右键来trigger？

**Comment by anc95** [comment]
@aceOrange 
是的，你说的没错，同时双击空白处也会唤醒 “W”

1. 快捷键会做的，计划是通过快捷键直接唤醒输入框进行交互，有点类似 Mac 的 (Command + Space) 的交互
2. 鼠标右键先不做，还没想好加什么

**Comment by aceOrange** [comment]
谢谢回答。期待快捷键！:)

**Comment by qlaall** [comment]
那么现在这个应用已经上架Chrome应用商店了吗？地址是什么？
"Has it been listed on the Chrome Web Store now? What's the address?"

**Comment by anc95** [comment]
@qlaall，非常抱歉还需要等待审核，一旦通过会第一时间向您报告。
"@qlaall, I'm sorry but it's still pending for review. I will inform you immediately once it's approved."

**Comment by tanruixiang** [comment]
@anc95 It seems that it has already been reviewed and can be found on the Chrome Web Store, but the version is a bit outdated.

**Comment by anc95** [comment]
@tanruixiang Thanks for your information. I had assumed they would send me an email update, but it seems that is not the case. I will check and request a new update version. Thank you.

**Comment by anc95** [comment]
Hey @tanruixiang, I wanted to let you know that I've made some updates to the readme for the installing part. Additionally, I submitted the latest package to the Chrome Web Store. Thank you once again for providing me with such helpful information. Your advice has been invaluable in making this project a success.

**Comment by tanruixiang** [comment]
> Hey @tanruixiang, I wanted to let you know that I've made some updates to the readme for the installing part. Additionally, I submitted the latest package to the Chrome Web Store. Thank you once again for providing me with such helpful information. Your advice has been invaluable in making this project a success.

Thank you very much for your efforts, this plugin has helped me a lot and I look forward to using the latest version on the Google Play Store.

**Comment by anc95** [comment]
@all 谷歌商店已经发布了 0.0.8 版本, 大家可以用这个版本了，相对比较稳当
https://chrome.google.com/webstore/detail/writely/eocenplmfgoaibmmohkhhocnlkpaecgn

**Comment by geekbb** [comment]
> @ALL 谷歌商店已经发布了 0.0.8 版本, 大家可以用这个版本了，相对比较稳当 https://chrome.google.com/webstore/detail/writely/eocenplmfgoaibmmohkhhocnlkpaecgn

大爱！！！完美代替notionai！
![image](https://user-images.githubusercontent.com/46196358/225306638-e304f9fa-0cb1-4971-b7bc-8a50dadffd10.png)
