### ISSUE TITLE
最新的0.9版本不能显示gpt的输出内容

### ISSUE THREAD

**Issue by alanjustalan** [anc95/writely#10]
https://user-images.githubusercontent.com/42884681/224542603-87bbf3bb-db70-4a59-8a22-a0bd7d2fa46e.mp4

**Comment by anc95** [comment]
@alanjustalan 确定下版本是 0.09 吗，我今天升级了样式，最新版本应该是下面这样

<img width="762" alt="image" src="https://user-images.githubusercontent.com/13167934/224543428-eef5b602-b74d-4f70-b497-1d7425738a8a.png">

**Comment by anc95** [comment]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/13167934/224543670-238d1f75-6035-4fe7-86e1-fff0803c4cd3.png">
再就是升级后有一个点语言会跑到左手边，更方便点击

**Comment by alanjustalan** [comment]
我说错了，是0..0.8版本，0.0.9版本还没发吧？插件显示有这两个错误
![image](https://user-images.githubusercontent.com/42884681/224544504-f96e5172-23ea-4bbd-b803-f408108442ac.png)
![image](https://user-images.githubusercontent.com/42884681/224544646-8a5a6fc1-d3e6-4cde-97be-688329eab66c.png)
![image](https://user-images.githubusercontent.com/42884681/224544666-9629a90f-f792-411f-8df3-684df52e4be6.png)
![image](https://user-images.githubusercontent.com/42884681/224544699-79aacef7-17eb-4dc3-bad8-f2b25d43d7e8.png)

**Comment by anc95** [comment]
@anc95 @alanjustalan 你的 Model 配置的什么

**Comment by alanjustalan** [comment]
gpt 3.5 turbo

**Comment by anc95** [comment]
> gpt 3.5 turbo

要不卸载重新安装试试，你视频的 UI 图看着也不是 0.0.8 的，可以看我截图的UI，优点奇怪

**Comment by alanjustalan** [comment]
我卸载了，删除了浏览器的缓存，重新装上又可以了。想问下大概什么时候能正式上chrome商店呢？好像提交审核有几天了吧？o(╥﹏╥)o

**Comment by anc95** [comment]
> 我卸载了，删除了浏览器的缓存，重新装上又可以了。想问下大概什么时候能正式上chrome商店呢？好像提交审核有几天了吧？o(╥﹏╥)o

还没消息 根据别人经验审核差不多得五六天吧，再就是提交的版本是 0.0.2，到时候还需要提交新版本
