### ISSUE TITLE
太棒了，这个插件，就是怎么自定义自己的菜单prompts

### ISSUE THREAD

**Issue by nudgee28** [anc95/writely#11]
太棒了，这个插件，就是怎么自定义自己的菜单prompts

**Comment by nudgee28** [comment]
主要是没有回复邮件的选项

**Comment by anc95** [comment]
@nudgee28 
那个输入框可以直接输入自己的指令的，你可以先这么用

我后续会加上一个功能就是把自定义的指令加到收藏夹，下次就能在下拉的选项里看到自定义的 prompt 了

**Comment by anc95** [comment]
@nudgee28 刚把这个功能简单实现了下，请下载 v0.0.9 版本使用

配置
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/13167934/224920920-5f46ba84-a98e-4cb8-99b7-8e7606e1c99c.png">

使用
<img width="623" alt="image" src="https://user-images.githubusercontent.com/13167934/224920996-131187cd-1fd6-4efc-acd8-77bf107dc65f.png">

**Comment by anc95** [comment]
> 太强了！

This is what a man should do.

**Comment by nudgee28** [comment]
爱你 比心❤ 这功能真的好有用啊！！！！

**Comment by anc95** [comment]
GPT 比较智能，可以自己解锁很多使用场景，如也可以用来画流程图
![image](https://user-images.githubusercontent.com/13167934/224950478-ae141de9-5811-4386-9014-61a4694ed9ef.png)

**Comment by nudgee28** [comment]
刚想了下如果可以的话后续这个功能还能再优化下
如果打的自定义prompts太长,显示的有点不大美观，最好能自设一个简短的标题
🤩

**Comment by anc95** [comment]
@nudgee28 UI 上自动截断用是不是可以

如显示为

```
长长长长长长长长长长长长长长...
```

基本看到前面的字就知道是哪个 prompt 了

设置 alias 可能多数情况都不用到，我们就直接在 UI 上简化下

**Comment by nudgee28** [comment]
嗯嗯，可以截取一段就行

**Comment by pytkr** [comment]
Love this extension, and I found ChatGPT Sidebar has a great user defined prompt UI, namely, user can give a name to each prompt, please consider make this extension include that UI.
