### ISSUE TITLE
建议增加右键菜单

### ISSUE THREAD

**Issue by nudgee28** [anc95/writely#12]
有些网页中文字，选中之后不弹出w，想说可不可以，右键菜单中添加下，呼出界面

**Comment by anc95** [comment]
可

@nudgee28 分享下链接，对应问题要修下

**Comment by nudgee28** [comment]
不好意思，因为需要账号密码登入的，不然进入不了页面

**Comment by nudgee28** [comment]
比如说 FeHelper 插件中
![image](https://user-images.githubusercontent.com/16789596/225198967-b5603a5f-6ff5-43d3-ab5b-854d0deb480a.png)

**Comment by anledehai** [comment]
> 可
> 
> @nudgee28 分享下链接，对应问题要修下

也是类似情况，建议添加快捷键？因为部分编辑器是占用右键的编辑功能，比如”flowus.cn/“这类在线的笔记应用

**Comment by nudgee28** [comment]
全局快捷键好像也是一个不错的选择

**Comment by izuolan** [comment]
+1 如果可以用全局快捷键, 不显示那个 w 按钮的话就更好了, 我看演示 demo 里 w 按钮都挡住了编辑器的菜单.

**Comment by nudgee28** [comment]
建议如果是右键的话，最好里面只显示自定义的就好了这样最方便，能排序那更好

**Comment by anc95** [comment]
这个功能安排在下个版本了 这两天比较忙 等着周末或者下周初弄一下

**Comment by anc95** [comment]
v0.0.10 已发布 https://github.com/anc95/writely/releases/tag/v0.0.10

支持右键菜单

等待 Chrome 商店审核中
