### ISSUE TITLE
内置prompt改进

### ISSUE THREAD

**Issue by devyujie** [anc95/writely#16]
内置的prompt可以再改进一下，老是出现“首先”“其次”“总之”“最后”等关键词，具体是`使内容更丰富`那个。
![image](https://user-images.githubusercontent.com/48620527/225821842-fb4021ee-88af-4c99-8440-bd7de28d86ea.png)

**Comment by anc95** [comment]
哈哈好的，也可以试试 edit text 的 model，那个是专门用于文本修改的，效果会好很多，不过也贵

我也发现一些 model 废话比较多，如 `提升写作`，最近试试优化一下

**Comment by anc95** [comment]
这里为了 prompt 的通用性，目前将内置 prompt 优化为

```
使内容更丰富：

${用户选中内容}
```

可以使用自定义指令自定义一些 Prompt，如 小红书风格生成器等
<img width="836" alt="image" src="https://user-images.githubusercontent.com/13167934/232029118-330b36ea-c346-4a86-8307-bad45fc325d5.png">
