### ISSUE TITLE
自定义api url无法工作

### ISSUE THREAD

**Issue by colin4k** [anc95/writely#24]
在选项中设置了自定义的api url后，点击'Test'按钮可以正常工作，但是实际使用时一直转圈没有返回。

**Comment by anc95** [comment]
谢谢，我看一看

**Comment by colin4k** [comment]
> 

看了一下插件管理的错误日志，貌似在实际使用时自定义的url不生效，报网络连接错误

**Comment by anc95** [comment]
@colin4k 我怀疑可能是跨域错误，你试试给你的 API 代理设置一下允许跨域头试一试

**Comment by colin4k** [comment]
> @colin4k 我怀疑可能是跨域错误，你试试给你的 API 代理设置一下允许跨域头试一试

大概知道是什么原因了，因为我的api proxy不支持https，在访问https的网页并使用插件时会先出现以下错误：
Mixed Content: The page at 'https://baijiahao.baidu.com/s?id=1760848053589375628' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxx.xxx.xxx/v1/chat/completions'. This request has been blocked; the content must be served over HTTPS.
然后再报一个网络连接错误。这个有办法可以支持吗？

**Comment by colin4k** [comment]
Uncaught (in promise) Error: Network Error
dist/content/index.js:70284 (匿名函数)
```
var require_createError = __commonJS({
  "node_modules/axios/lib/core/createError.js"(exports, module2) {
    "use strict";
    var enhanceError = require_enhanceError();
    module2.exports = function createError(message2, config2, code, request3, response) {
      ==var error3 = new Error(message2);==
      return enhanceError(error3, config2, code, request3, response);
    };
  }
```

**Comment by anc95** [comment]
@colin4k 老哥你那有免费的代理，或者部署代码的方法吗？我自己测一下

**Comment by anc95** [comment]
我估计还是跨域等原因（毕竟在 options 页面里你是可以访问的呢

其中一个方式是，通过 backrgound.js 代理下请求，应该是可以解决跨域问题
https://developer.chrome.com/docs/extensions/mv3/xhr/#xhr-vs-content-scripts

**Comment by colin4k** [comment]
> 

[openai-proxy](https://github.com/Ice-Hazymoon/openai-scf-proxy/)，可以通过腾讯云函数部署

**Comment by colin4k** [comment]
> 我估计还是跨域等原因（毕竟在 options 页面里你是可以访问的呢
> 
> 其中一个方式是，通过 backrgound.js 代理下请求，应该是可以解决跨域问题 https://developer.chrome.com/docs/extensions/mv3/xhr/#xhr-vs-content-scripts

好的，我试试，谢谢。

**Comment by anc95** [comment]
@colin4k 你那里如何了

因为腾讯云之前玩欠费了，我今天试了下用 cloudflare 部署了一个代理，是没问题的
<img width="598" alt="image" src="https://user-images.githubusercontent.com/13167934/227909036-d12df9d4-19fc-4a84-ad05-60b2d718063e.png">

https://github.com/fuergaosi233/openai-proxy 用的这个项目部署的

**Comment by colin4k** [comment]
> @colin4k 你那里如何了
> 
> 因为腾讯云之前玩欠费了，我今天试了下用 cloudflare 部署了一个代理，是没问题的 <img alt="image" width="598" src="https://user-images.githubusercontent.com/13167934/227909036-d12df9d4-19fc-4a84-ad05-60b2d718063e.png">
> 
> https://github.com/fuergaosi233/openai-proxy 用的这个项目部署的

谢谢关注，在cloudflare上重新部署代理之后ok了
