### ISSUE TITLE
Support firefox

### ISSUE THREAD

**Issue by icefed** [anc95/writely#26]
Thank you.

**Comment by anc95** [comment]
@icefed 

Absolutely, I will ensure to test on Firefox and will soon publish it on the Firefox add-on platform in the coming days.

**Comment by mmiris** [comment]
可以支持 Safari 吗？❤️‍🔥

**Comment by anc95** [comment]
@icefed 

Please download v0.0.11, which now supports Firefox add-ons. The download link is https://github.com/anc95/writely/releases/tag/v0.0.11.

**Comment by anc95** [comment]
@mmiris safari 因为 API 和 firefox/chrome 等差异较大，比较耗费精力，所以暂时先不支持

**Comment by mmiris** [comment]
@anc95 好的👌

**Comment by icefed** [comment]
> @icefed
> 
> Please download v0.0.11, which now supports Firefox add-ons. The download link is [`v0.0.11` (release)](https://github.com/anc95/writely/releases/tag/v0.0.11).

@anc95 请问要怎么使用？
下载后点击 `Install addon from file` 报错`corrupt`.

**Comment by icefed** [comment]
> @icefed 解压后加载根目录的 manifest.json 就行

谢谢，可以用了。

有计划发布到 Firefox Add-ons 市场吗？

**Comment by icefed** [comment]
已上线： https://addons.mozilla.org/en-US/firefox/addon/writely/


提两个 BUG，点击`更多`没有用；在 issue 恢复框里选择文本没有弹出`W`按钮，界面选择文本可以。
