### ISSUE TITLE
建议：自定义promt支持修改

### ISSUE THREAD

**Issue by 6uu1** [anc95/writely#29]
现在只能删了再写，要是加上修改功能就好了

**Comment by anc95** [comment]
是的，这个挺刚需

计划会做 prompt 的基本增删差改
还有导入导出 json （方便不同账号之间共享）

**Comment by anc95** [comment]
prompt 的 新增 / 删除 / 修改 / 置顶 / 导入 / 导入 已经在 v0.0.16 支持了
