### ISSUE TITLE
界面显示异常

### ISSUE THREAD

**Issue by 6uu1** [anc95/writely#30]
![image](https://user-images.githubusercontent.com/122669698/227696435-d43e81b4-9da7-4df3-9a7b-2b945c46b267.png)

**Comment by anc95** [comment]
样式加载问题，下一个版本修复下

**Comment by anc95** [comment]
@6uu1 最新版本已经修复了，我先 close 掉了

**Comment by 6uu1** [comment]
> @6uu1 最新版本已经修复了，我先 close 掉了

好，辛苦开发大大了
