### ISSUE TITLE
Azure OpenAI API 支持

### ISSUE THREAD

**Issue by tookdes** [anc95/writely#66]
现有只支持 OpenAI 的接口形式，希望可以参考其他家开发对 Azure OpenAI API 的支持

**Comment by anc95** [comment]
你好，有可以提供参考的产品吗

**Comment by tookdes** [comment]
https://github.com/jack482653/openai-slack-bot/issues/14#issuecomment-1555918774

请您参考其他家的产品和 Azure OpenAI 官方的说明，修改一下 base URL 和调整一下模型名字的变量之类的就可以了。

**Comment by keung67** [comment]
Azure OpenAI API可以填入代理來用
[cf-openai-azure-proxy](https://github.com/haibbo/cf-openai-azure-proxy) + Cloudflare worker

Writely代理網址：
從 Cloudflare worker 取得 URL最後加入/v1
例如 https://cf-openai-azure-proxy.username.workers.dev/v1
