### ISSUE TITLE
是否考虑支持多模型的部署

### ISSUE THREAD

**Issue by petter529** [anc95/writely#68]
llama等开源模型,以及微调的故事模型,在写作能力上都不错,是否考虑支持对多模型的支持OpenAI接口的API支持

**Comment by Adsryen** [comment]
现在很多都会用[one-api](https://github.com/songquanpeng/one-api)去做key的中转，这样会适配国内外诸多模型，我觉得应用添加一个用户可以自定义模型名称的方案是最便捷也最适众的一个思路

包括使用openai最新的模型gpt-3.5-turbo-0125、gpt-4-0125-preview，也就完全不需要你这边修改过多代码，通过用户自定义模型最方便

**Comment by anc95** [comment]
好的，最近会尽快支持一下

**Comment by anc95** [comment]
<img width="1007" alt="image" src="https://github.com/anc95/writely/assets/13167934/acc567b0-e0b5-4e28-9cb6-cee27e1d2f0e">
UI 已更新，支持手动输入模型，默认三种模型点击后快速填写

**Comment by uxfion** [comment]
> UI 已更新，支持手动输入模型，默认三种模型点击后快速填写

大佬您好，我尝试过使用`gpt-3.5-turbo-0125`、`gpt-4-0125-preview`，好像都无法正常使用
![image](https://github.com/anc95/writely/assets/44778029/83fb7f47-ed39-4481-8b50-e38d8727c750)


此外，默认的`gpt-3.5-turbo`后台实际上会调用`gpt-3.5-turbo-0613`
![image](https://github.com/anc95/writely/assets/44778029/cfda2142-5bae-4b8d-8acd-ab55eb18ec6c)


同时针对`gpt-3.5-turbo`系列，似乎都会加上后缀`-0613`，导致异常
![image](https://github.com/anc95/writely/assets/44778029/8f52702b-2676-49c0-848d-542f40400d83)

不清楚是不是这个版本引入的bug

**Comment by anc95** [comment]
@uxfion 是的，已修复提交，等待 Chrome 商店审核中

**Comment by Adsryen** [comment]
希望也可以同步edge浏览器的拓展商店

**Comment by uxfion** [comment]
> @uxfion 是的，已修复提交，等待 Chrome 商店审核中

感谢！这个项目真的非常awesome

**Comment by anc95** [comment]
> 希望也可以同步edge浏览器的拓展商店

@Adsryen 已经提交审核了，edge 可能比较慢
