### ISSUE TITLE
一直不出现内容，配置那里测试是正常

### ISSUE THREAD

**Issue by Tomleolt** [anc95/writely#69]
![Snipaste_2024-04-08_10-18-42](https://github.com/anc95/writely/assets/139877178/b73e950e-f317-4e9b-8348-d7f3add9b037)

**Comment by Tomleolt** [comment]
我是在notion网页中使用，是不支持？

**Comment by anc95** [comment]
支持的，是使用的 OpenAI 官方的 服务地址吗
