### ISSUE TITLE
希望可以支持deepseek

### ISSUE THREAD

**Issue by wptoux** [anc95/writely#70]
Deepseek模型可以国内访问，比gpt-3.5效果好，而且成本更低。当前问题是model设置成deepseek-chat时，调用的不是chat接口，导致返回异常。

![image](https://github.com/anc95/writely/assets/6761483/32804e08-7c89-429b-ad33-45b4887a77d2)
或许一种可能的修复方式是修改如下代码，把默认情况改成使用chat？
https://github.com/anc95/writely/blob/3faed52cec9b5f52d8504bfef2f970585233eb3c/src/common/api/openai.ts#L70-L73

**Comment by anc95** [comment]
> To be compatible with OpenAI, you can also use https://api.deepseek.com/v1 as the base_url. But note that the v1 here has NO relationship with the model's version.

试试改成 https://api.deepseek.com/v1

**Comment by wptoux** [comment]
> > To be compatible with OpenAI, you can also use https://api.deepseek.com/v1 as the base_url. But note that the v1 here has NO relationship with the model's version.
> 
> 试试改成 https://api.deepseek.com/v1

这个v1接口可能下线了。

![image](https://github.com/anc95/writely/assets/6761483/ad34fe74-2e71-4b3c-93c8-c94abc5a1e7c)

**Comment by anc95** [comment]
https://api.deepseek.com/v1/chat/completions

我看你的截图里请求中少了一个 chat

**Comment by anc95** [comment]
<img width="776" alt="image" src="https://github.com/anc95/writely/assets/13167934/7f299775-6391-4362-a673-e69de8eb3237">
是不是你的插件版本不对，应该一直用的是 messages

**Comment by wptoux** [comment]
![image](https://github.com/anc95/writely/assets/6761483/dab81be6-0ffd-46e6-bd12-f84de3ef44f0)
我看这个逻辑，似乎是只有gpt-4，名字里带turbo的，还有是writely service的，是走chat接口。

**Comment by anc95** [comment]
@wptoux 哦对，谢谢，我处理一下

**Comment by anc95** [comment]
@wptoux 商店已经更新了，你那边再试一试
