### ISSUE TITLE
非https的代理网址卡住

### ISSUE THREAD

**Issue by commiyou** [anc95/writely#73]
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/9b29e7c4-8e73-4f83-8c53-01f4055a7793">

**Comment by anc95** [comment]
@commiyou 代理设置下允许跨域试试

**Comment by commiyou** [comment]
咋设置？
我是自己用fastapu搭建的服务，包装了公司的接口成openai格式。

**Comment by anc95** [comment]
fastapi 参考下这个文档
https://fastapi.tiangolo.com/tutorial/cors/#cors-preflight-requests

**Comment by commiyou** [comment]
赞，解决了 多谢
