### ISSUE TITLE
可以填多个key吗?

### ISSUE THREAD

**Issue by alanjustalan** [anc95/writely#9]
如果可以填多个key的话，那速度是不是会更快?能自动切换key，缓解调用频率限制吗?

**Comment by anc95** [comment]
@alanjustalan 
1. 多个 key 对速度没什么影响，因为是单机使用的，一次只会发一个请求
2. 关于 Rate Limit, 我找了下 Open AI 的文档

<img width="824" alt="image" src="https://user-images.githubusercontent.com/13167934/224529489-4c61ecd6-4398-4e53-9a81-40980323727e.png">

如 Edit model，请求的限制是 20 次/每分钟，Token 的限制是 15000 个 次个分钟

如果是你自己的 Token 且单机使用，一分钟基本不会达到 rate limit 的

**Comment by alanjustalan** [comment]
好的，非常感谢！
